version: '3.9'
services:
    car-managment:
      container_name: car-managment
      build : .
      environment:
        NODE_ENV: production
        LOG_LEVEL: info
        MONGO_USER: admin
        MONGO_PASSWORD: password
        MONGO_PATH: mongodb:27017/cars
        PORT: 8080
        API_KEYS: pzNbH9kYKUtHPiUcy4tOXQ==,rLDHI/th2aIKkhVdPbdAAA==
      ports:
        - "8080:8080"
      depends_on: 
        - mongodb   
    mongodb:
      image: mongo:latest
      container_name: mongodb
      ports:
        - 27017:27017
      environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: password
      volumes:
        - mongo-data:/data/db
    mongo-express:
      image: mongo-express
      container_name: mongo-express
      ports:
          - 8081:8081
      environment:
        ME_CONFIG_MONGODB_SERVER: mongodb
        ME_CONFIG_MONGODB_ADMINUSERNAME: admin
        ME_CONFIG_MONGODB_ADMINPASSWORD: password
      depends_on: 
        - mongodb
volumes:
  mongo-data:
    driver: local        